### ISSUE TITLE
Setup troubles

### ISSUE THREAD

**Issue by jordana309** [lanl/EXSAN#4]
I had a few problems getting set up:

1. The ENDF-B/VIII library downloads as a .zip file, so the untar-ing script failed. Suggestion: if tar fails, use zip.
2. The ENDF-B/VIII library download, when unzipped, uses .endf for the extension rather than the .txt of earlier ones, so the auto-search for .txt found only readmes. Suggestion: check first for .endf only (to avoid finding the readme.txt files), and if none exist, search for .txt.
3. tk fonts looked terrible--turns out this is an anaconda thing, and I was able to fix it by creating a soft link to my system's tk file (a la the "horrible thing" from [this link](https://stackoverflow.com/questions/47769187/make-anacondas-tkinter-aware-of-system-fonts-or-install-new-fonts-for-anaconda/47787749#47787749))
4. The periodic table was crammed into a small space and I couldn't figure out how to expand it (I would have liked to be able to dynamically adjust the size of the bottom pane)
5. Sometimes, when I select a library, I get the following message (see terminal window of Problems.png attached), and the tk window would freeze up.

That said, this program does awesome things, and I can't wait to tear into it!

![Problems](https://user-images.githubusercontent.com/10908984/55421107-c0560000-5535-11e9-9ef1-eaf4ea3b0703.PNG)

**Comment by jordana309** [comment]
Update: the previous screen resolved to two blank tk windows with the title EXSAN 1.0. When I closed them, the terminal changed to the following and the Periodic table showed up.
![Problems](https://user-images.githubusercontent.com/10908984/55421395-60ac2480-5536-11e9-90cd-be21fafbae76.PNG)

**Comment by omarwooten** [comment]
Thanks for the feedback! One other user has also reported issues during setup on MacOS, although I think they are the result of incomplete communication on my part. I've been working to streamline the setup process, so if you're willing to try, please get a fresh checkout of the `master` branch. 
`python exsan.py -h` will show you options available, including one for linking to your NJOY2016 executable.  An updated tutorial should be available later this week.
